CREATE TABLE pauta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(140) NOT NULL,
    descricao VARCHAR(2000),
    criada_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_pauta_titulo CHECK (CHAR_LENGTH(TRIM(titulo)) > 0)
);

CREATE TABLE sessao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pauta_id BIGINT NOT NULL,
    aberta_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    encerra_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_sessao_pauta FOREIGN KEY (pauta_id) REFERENCES pauta(id),
    CONSTRAINT uq_sessao_pauta UNIQUE (pauta_id),
    CONSTRAINT ck_sessao_periodo CHECK (encerra_em > aberta_em)
);

CREATE TABLE voto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pauta_id BIGINT NOT NULL,
    associado_id VARCHAR(64) NOT NULL,
    voto VARCHAR(3) NOT NULL,
    registrado_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_voto_pauta FOREIGN KEY (pauta_id) REFERENCES pauta(id),
    CONSTRAINT uq_voto_pauta_associado UNIQUE (pauta_id, associado_id),
    CONSTRAINT ck_voto_opcao CHECK (voto IN ('SIM', 'NAO')),
    CONSTRAINT ck_voto_associado CHECK (CHAR_LENGTH(TRIM(associado_id)) > 0)
);

CREATE INDEX ix_pauta_criada_id ON pauta (criada_em DESC, id DESC);
CREATE INDEX ix_voto_pauta_opcao ON voto (pauta_id, voto);
